executors:
  centos-build-executor:
    docker:
      - image: opennms/build-env:17.0.1_12-3.8.4-b7902
  debian-build-executor:
    docker:
      - image: opennms/build-env:debian-jdk17-b7901
  docker-executor:
    docker:
      - image: docker:20.10.1-git
  docs-executor:
    docker:
      - image: opennms/antora:2.3.4-b6293
  integration-test-executor:
    machine:
      image: ubuntu-2004:202010-01
  smoke-test-executor:
    machine:
      image: ubuntu-2004:202010-01
  ui-executor:
    docker:
      - image: cimg/node:16.3.0
